language: scala
scala:
- 2.11.4
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
sudo: false
branches:
  only:
  - master
  - /^[0-9]+\.[0-9]+\.[0-9]+$/
cache:
  directories:
  - $HOME/.m2
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && echo "Not a PR Build" && [ "IS_${TRAVIS_TAG}"
  != "IS_" ] && echo "Is tag build $TRAVIS_TAG" || echo "."'
- '[ "IS_${TRAVIS_TAG}" != "IS_" ] && mvn versions:set -DnewVersion=$TRAVIS_TAG ||
  true'
install:
- mvn clean install -Dmaven.javadoc.skip=true -B -V
before_script:
- test "$TRAVIS_PULL_REQUEST" == "false" && git clone -b travis `git config --get
  remote.origin.url` target/travis || true
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && echo "Deploying..." && mvn deploy --settings
  target/travis/settings.xml || echo "Testing..." && mvn test -B'
env:
  global:
  - MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
  - secure: U0cV/x0fOL1userPTApIodYefLgX2edpOdOQR7y9aN/j7zW2tI4oF+xv4uXtWhY08O0BpYsUBCyLMiCusKCUxs7tJNacGmCBD8LZ39Och0V3l5H0LXxasgv93H3RirkaYx5T1RVI9QOQl2+uroVEEVmyABPPQg9DBU8xsU+DPCTAxq++i3XK4exNJ+WEnga66No0K+Rdg4FAClpOE9DnITq5PYBXm3ohLAB5uGstLGe8yl12IGIhtCdcfcI+U4pS0pGbfsNdgTkrtOxe0uNh2PVBndKD0h54sxU8Q5HZMrSdpogoLPRqpDX6Q5D5Ho1ZGDLBiUb6le8mEvNIgcd5vO7CA7jYzjDwZSd8dI1FmQYAPo8WlDr32CePRGoo2ABW0x7byShh+4XrCEx3BU4svnQ4RjCauBmS1kPpFBsJ7bYj3sG8SQboY7yhz9sU4rgeRjtCdlKtWsyAM7uhXxT2zwJcDOH/jaFhlWHvW6B6xNANGBQC3rKHDg61qV5+YjfIX6+irMGd7GdMzMk/hc1QOY58a+fdD1zI1opvQN5zhbLsUiyx0Aq3zFcoqCw//KBCJGv9XmBu2RAi+7MREr+TqLiqqapi/K8g1fB0x+O5+kyz7w4jMLCDyOgJh6Eomi09+zfQhWIfeyr8ZST3cVr3ANXz+HCgEUvilSSlMw7JgSk=
- secure: "KAV/03jby01bmOPxRvGmeu+ou6+WDf6T/qiwtDzAzZUXUA8YiOsLUJl/yFleWfnCE/n3/iIKAD24bZj363sCzxpXhOl/UdoLFl1WCG0GntBN7HwcuJViRB3eCbIfllRpP34is8QvZIWWdpJek5qOr7DzdtPfekG/nn9SB96NYbyjGKHd/jAEleC61xikX9k8hQPX/tZVRaBBrkH8XTNCPQI4jyBLgBgJHazRkyhKXtnm/q9kgCfMPKEzCFDJKRZTY5TydZ7QdEcoJgP67bS7V/YQ3vzk5YT3s2PQVLKKWP2ptUFXq6DtOgRJgxqSkkZW0nXEoxbFzQi2huZ40oMOQXQNHGXAGBva+KJG3iEzmtaIIbMa0AS8wV5ZLYgX7cIreyXu9s+u6238Y1oahGEGO5mTPbnB1iTkEQyLvCk29DIkTfstcbDldHkAYFLGhjUn5S4VBghEfDmveKMXam9FygZprc0E+YmbkoMy2QpkzjnKA3xlnFbBGjdYEJ6qRjXD3aW8o02NiWnZse+5D+17mtG/C/9xsZTu/so7wQVHTDGoxv/vaAQueQMezXVs1xncdxAQHifrYcJ6KOrEHcVEzJE4ARx9tZxWictKjMPQ/tkc4QayRwYbCQ18L1mD4bMghxoaSsfL/v3pLcrvM4f+axdabMMykfJzGUVEijRzuQM="
  - secure: "bQDT4xzzSco5iK+6YTPaztHNIyaVxg4k+C46Cqgb9liZWsV7mwnoDmFJP782WMKR62simlu5MDOiKYj3gLohiRaLhE4vOw+oWxGjTgL6WIZflcbQ2GuluE9FLfK2qBzlbEeF7W/tVWifiiPP7Yg/hknncNuKsmm/bH1PQDvCVJaMX1TeA72ssXflPn8pI40Za7J0Ahcnx9BHhvuk0QSIuxUoWED1D7O/DfBMyMxWTUm/Ng6SnsfzbNSz7TIsRhPurvrQ+j9a7xG8R1TGOUFJcOE8fRAvOApNpBQ+PdV0BFBIt/0Y++Orvjf9YEdE9eD2rsIU4M3R+oW/7wH55JstJWZmX+4MpE0euYuqYFHJd5pbVG9tOkKUPLdEqs9ZJxKN5kRTPohmHbQp30ESMoawyyoM71pWqV9yIwODaUEp4500u4tCEc+ITwMxuqhcvfTCDvYDbtvVgmPCz5b0Ujtax4mYhbOdrNs3AVIj/b52krFLm6RodtOIowxop7m8Nz9L2rJ/o+ZU76XHS5imuGDJUy2zKrLUYkqJ2Q7wNchr28JHBphBTYsDiEMWTruHPVbQ0BPQuTsSpbstLgcg6QX0KzWaYqVtO5Eijkn1d7a/tkvdfT35SeE77ZId79snjXfK8CjyPD1J8WPy5HaT1uhptK1NENQZF8GoC/pd+9hr1xw="
  - secure: "F0BOEjLcT09tRieA3ElUeEYnmTtOHgHe3lrDgKsFBFgX3f77HZwGzSSNkpX+wXiBzlIdrpS55vc8LTjeoqbyOp4NB+0XHP2Z31DjjNNWQa0MrmrcxD8AycJu4NUO27XCE6R33ttGYMRTyvgKVTvfZzQxs5aDK1STKMmbfZLwIndtJrESuEl3wbai1slHu15/Z1ekte3Ag+gilLrMJqUp4f3I9Pxu2fov5WmA7kHcnWtuaNrKzcMQ+KRF6LKi+evvw/HmJPaY47bS10KEitQjVP0MEMOVXRoul57o0dKFKtrvYWX1KbwTq7Xv8emSg4YjDqkOecV/02nisa8z0pKCfRSTAf6aTHQrUDx83ClMTGu6E57CA37qh/3HdOIr8PR+AAIMl+ks+9BE5SfTZv/tuzbBgwovTTKwwD6HGpI15cQwrw72iVYqt/K8yWKtzmUiXbQTDCG2bTHa8DHvnximLntKS96oKFXqt0kDG7VbePPz42nPe0RJRd10EdTXFSnte1Vd99XXz3+cqP7LIWMkkrndLVmBx71v6VqP3JuOwppSNGZsuHK7MYW9wI8eJcYnFR8pB2HLKAfujthe7NubG8A50xf+UFL/yYt+mubUUQSuGMojNOOz6vQCPIbby2aVcWvWCLBVI/PCkeCtN/BbJX6RjTLajCLSh3bil0BhLog="
